---
title: "Static Graphics"
output: html_document
date: "2023-06-08"
---


```{r}
library(tidyverse)
library(readr)

course_reg_data <- read_csv("course_reg_data.csv")
```

yearly graph
```{r}
test_min <- course_reg_data |> filter(course == "A Bridge to Higher Math")
ggplot(data = test_min, aes(x = reporting_year, y = yearly_enrolled)) +
  geom_line() +
  geom_point()
```

semester graph
```{r}
ggplot(data = test_min, aes(x = reporting_year)) +
  geom_line(aes(y = FA)) +
  geom_point(aes(y = FA)) +
  geom_line(aes(y = SP)) +
  geom_point(aes(y = SP)) +
  labs(x = "Year", y = "Enrollment")
```

```{r}
test_max <- course_reg_data |> rename("FA" = "fall_enrolled",
                                      "SP" = "spring_enrolled") |>
  pivot_longer(cols = c(FA, SP),names_to = "semester", values_to = "semester_enrolled") |> 
  filter(course == "Algorithm Analysis") |> 
  mutate(order = case_when(
  semester == "SP" ~ as.numeric(reporting_year),
  semester == "FA" ~ as.numeric(reporting_year) + 1)) |> 
  unite("term", c(reporting_year, semester)) |>
  mutate(term = fct_reorder(term, order, .desc = FALSE)) 
test_max <- test_max |> filter(semester_enrolled != 0)
View(test_max)

```


ADDING SECTION POINTS TO GRAPHIC
```{r}
course_reg_data <- read_csv("course_reg_data.csv")
course_reg <- course_reg_data |> pivot_longer((c(6:43)), names_to = "semester", values_to = "enrolled") |>
  filter(enrolled != 0) 
course_reg <- course_reg |> separate(col = semester, into = c("semester", "section"), sep = "_")
course_reg <- course_reg |> unite("term", c(reporting_year, semester))
course_reg <- course_reg |> filter(course== "Algorithm Analysis")
View(course_reg)
```

```{r}
ggplot(data = test_max, aes(x= term, y = semester_enrolled, group = 1)) +
  geom_line()+
  geom_point()+
  scale_x_discrete(limits = levels(test_max$term)) +
  geom_point(data = course_reg, aes(x = term, y = enrolled, group = 1), alpha = 0.5) +
  theme(axis.text.x = element_text(angle = 90))
```


fixing the graph to be a cumulative sum
```{r}
course_reg_data <- read_csv("course_reg_data.csv")
course_reg_section <- course_reg_data |> 
  pivot_longer((c(6:43)), names_to = "semester", values_to = "enrolled") |>
  filter(enrolled != 0) 
course_reg_section <- course_reg_section |> separate(col = semester, into = c("semester", "section"), sep = "_")
course_reg_section <- course_reg_section |> mutate(year = reporting_year) |>
  unite("term", c(reporting_year, semester))
course_reg_section <- course_reg_section |> group_by(course, term) |> 
  mutate(cumulative_enrolled = cumsum(enrolled)) |> filter(course == "MATH-280: A Bridge to Higher Math")
course_app_section3 <- course_reg_section |> group_by(term) |> summarise(total_sections = n())
course_reg_section <- left_join(course_reg_section, course_app_section3, by = c("term"))

```

```{r}
plot <- ggplot(data = course_app_semester, aes(x = term, y = semester_enrolled, label = semester_enrolled, group = 1)) +
          geom_line() +
          geom_point() +
          geom_point(data = course_app_section, aes(x = term, y = cumulative_enrolled, label = enrolled, group = 1), alpha = 0.25) +
          theme(axis.text.x = element_text(angle = 90)) 
ggplotly(plot)
```



graphing enrollment by level of course in each discipline
```{r}
test <- course_reg_data |> mutate(level = case_when(
  as.numeric(`Course Number`) >= 1000 ~ as.numeric(`Course Number`) %/% 1000 - 1,
  as.numeric(`Course Number`) < 1000 ~ as.numeric(`Course Number`) %/% 100))
test <- test |> filter(Subject == "MATH")
test <- test |> group_by(level, reporting_year) |> summarise(enrolled = sum(yearly_enrolled))
test <- test |> filter(level <=3)
###
course_reg_section <- course_reg_data |> 
  pivot_longer((c(6:43)), names_to = "semester", values_to = "enrolled") |>
  filter(enrolled != 0) 
course_reg_section <- course_reg_section |> separate(col = semester, into = c("semester", "section"), sep = "_") |> mutate(year = reporting_year)
course_reg_section <- course_reg_section |> unite("term", c(reporting_year, semester))
###
section_total <- course_reg_section |> mutate(level = case_when(
  as.numeric(`Course Number`) >= 1000 ~ as.numeric(`Course Number`) %/% 1000 - 1,
  as.numeric(`Course Number`) < 1000 ~ as.numeric(`Course Number`) %/% 100))
section_total <- section_total |> filter(Subject == "MATH")
section_total <- section_total |> group_by(year, level) |> summarise(total_sections = n()) |> rename("reporting_year" = "year")
section_total <- section_total |> filter(level <=3)
test <- left_join(test, section_total, by = c("reporting_year", "level"))
test <- test |> mutate(avg_section = round((enrolled/total_sections)))
View(test)
plot <- ggplot(data = test, aes(x = reporting_year, y = enrolled, color = factor(level), label = total_sections, label2 = avg_section)) +
  geom_point() +
  geom_line()+
  labs(color ="Course Level") +
  theme_minimal()
ggplotly(plot, tooltip = c("label", "y", "label2"))
```

```{r}
course_app_yearly <- course_reg_data |> filter(course == "A Bridge to Higher Math")
course_reg_section <- course_reg_section |> group_by(year) |> summarise(total_sections = n()) |> rename("reporting_year"="year")
newdata <- left_join(course_app_yearly, course_reg_section,
          by= c("reporting_year"))
plot1 <- ggplot(data = newdata, aes(x = reporting_year, y = yearly_enrolled, group = 1, label = total_sections)) +
       geom_line() +
       geom_point() +
       labs(
       x = "Year",
       y = "Enrollment") + 
       theme_minimal()+
       theme(axis.text.x = element_text(angle = 90, vjust=0.5,hjust=1))
ggplotly(plot1)
```

plot that shows open seats on top of enrollment
yearly
```{r}
course_reg_data <- read_csv("course_reg_data.csv")
course_app_yearly <- course_reg_data |> filter(course == "MATH-280: A Bridge to Higher Math")
course_reg_section <- course_reg_section |> group_by(year) |> summarise(total_sections = n()) |> rename("reporting_year"="year")
newdata <- left_join(course_app_yearly, course_reg_section,
          by= c("reporting_year"))
newdata <- newdata |> mutate(total_capacity = capacity*total_sections)
View(newdata)
plot1 <- ggplot(data = newdata, aes(x = reporting_year)) +
       geom_col(aes(y = yearly_enrolled, fill = "Enrollment")) +
       geom_col(aes(y = total_capacity, fill = "Enrollment Capacity"), alpha = 0.5) +
       scale_fill_grey()+
       labs(
       x = "Year",
       y = "Enrollment",
       fill = "") + 
       theme_minimal()+
       theme(axis.text.x = element_text(angle = 90, vjust=0.5,hjust=1))
ggplotly(plot1)
```

semester
```{r}
course_app_semester <- course_reg_data |> 
          rename("FA" = "fall_enrolled",
                 "SP" = "spring_enrolled")|>
          pivot_longer(cols = c(FA, SP),names_to = "semester", values_to = "semester_enrolled") |> 
          filter(course == "MATH-280: A Bridge to Higher Math") |> 
          mutate(order = case_when(
            semester == "SP" ~ reporting_year,
            semester == "FA" ~ reporting_year + 1)) |> 
          unite("term", c(reporting_year, semester)) |>
          mutate(term = fct_reorder(term, order, .desc = FALSE)) 
        course_app_semester <- course_app_semester |>
          filter(semester_enrolled != 0)
        course_app_section <- course_reg_section |> group_by(course, term) |> mutate(cumulative_enrolled = cumsum(enrolled))
        course_app_section <- course_app_section |> 
          filter(course == "MATH-280: A Bridge to Higher Math")|>
          filter(enrolled != 0)
        course_app_section3 <- course_app_section |> group_by(term) |> summarise(total_sections = n())
        course_app_semester <- left_join(course_app_semester, course_app_section3,
                                         by = c("term"))
        course_app_semester <- course_app_semester |> mutate(avg_section = round(semester_enrolled / total_sections))|>
          mutate(term = fct_reorder(term, order, .desc = FALSE)) |> mutate(total_capacity = capacity*total_sections)
plot1 <- ggplot(data = course_app_semester, aes(x = term)) +
       geom_col(aes(y = semester_enrolled, fill = "Enrollment")) +
       geom_col(aes(y = total_capacity, fill = "Enrollment Capacity"), alpha = 0.5) +
       scale_fill_grey()+
       labs(
       x = "Year",
       y = "Enrollment",
       fill = "") + 
       theme_minimal()+
       theme(axis.text.x = element_text(angle = 90, vjust=0.5,hjust=1))
ggplotly(plot1)
```

```{r}
tester <- course_reg_data |> filter(course == "CS-140: Intro to Computer Program")
View(tester)
```

```{r}
course_reg_data
```

```{r}
      course_app_semester <- course_reg_data |> 
        rename("FA" = "fall_enrolled",
               "SP" = "spring_enrolled")|>
        pivot_longer(cols = c(FA, SP),names_to = "semester", values_to = "semester_enrolled") |> 
        filter(course == "CS-140: Intro to Computer Program" ) |> 
        mutate(order = case_when(
          semester == "SP" ~ reporting_year,
          semester == "FA" ~ reporting_year + 1)) |> 
        unite("term", c(reporting_year, semester)) |>
        mutate(term = fct_reorder(term, order, .desc = FALSE))
View(course_app_semester)
```








